DEFAULT_G5K_SITE := "grenoble"
export JUST_DIR := justfile_directory()

alias r := rsync_g5k
alias cpj := g5k_scp_justfile

default:
    @just --list

g5k_scp_justfile SITE=DEFAULT_G5K_SITE:
    scp justfile {{ SITE }}.g5k:oar-

# Rsync current worktree to G5K
rsync_g5k SITE=DEFAULT_G5K_SITE:
    #!/usr/bin/env bash
    set -euxo pipefail
    cd ../../
    rsync -avz oar-nixos-compose --delete --exclude '\#*' --exclude '*/build' --exclude '*/deploy' --exclude '*/artifact' --exclude  '*~' {{ SITE }}.g5k:
#oarsub    
oarsub NB_NODES="4":
    export $(oarsub -l nodes=NB_NODES,walltime=1:0:0 "$(nxc helper g5k_script) 1h" | grep OAR_JOB_ID)

deploy:
    nxc start -m OAR.$OAR_JOB_ID.stdout -W

